apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beta.kbhbilleder.dk
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: beta.kbhbilleder.dk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: beta-kbhbilleder-proxy
            port:
              number: 80
  tls:
  - secretName: beta.kbhbilleder.dk-tls
    hosts:
    - beta.kbhbilleder.dk
