apiVersion: v1
kind: Service
metadata:
  name: beta-kbhbilleder-proxy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: beta-kbhbilleder-proxy
subsets:
- addresses:
  - ip: 35.190.72.227
  ports:
  - port: 80
    protocol: TCP
