apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: cron
  name: cron
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cron
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: cron
    spec:
      containers:
      - env:
        - name: KBH_ACCESS_KEY
          value: kzZMj7SJgUQ83hhvx9eERk4X
        - name: JOB_NAME1
          value: Incremental
        - name: JOB_COMMAND1
          value: curl 'http://frontend/index/recent?timeframe=70m&accesskey=$(KBH_ACCESS_KEY)'
        - name: JOB_TIME1
          value: 02 02 0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
            * * *
        - name: JOB_NAME2
          value: Full
        - name: JOB_COMMAND2
          value: curl 'http://frontend/index/all?accesskey=$(KBH_ACCESS_KEY)'
        - name: JOB_TIME2
          value: 02 12 4 * * *
        image: blacklabelops/jobber:cloud
        name: cron
        resources:
          limits:
            memory: 50Mi
