apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
  namespace: production
  labels:
    component: elasticsearch
spec:
  replicas: 1
  selector:
    component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - command:
        - sh
        - -c
        - sysctl -w vm.max_map_count=262144 && /run.sh
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: kbh-billeder-es-cluster
        - name: DISCOVERY_SERVICE
          value: elasticsearch
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: NETWORK_HOST
          value: _local_,_site_
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.6.4
        name: elasticsearch
        resources:
          limits:
            memory: 2000Mi
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
          privileged: true
        volumeMounts:
        - mountPath: /data
          name: es-storage
      volumes:
      - name: es-storage
        gcePersistentDisk:
          fsType: ext4
          pdName: es-production-disk-new
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: production
  labels:
    component: elasticsearch
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elasticsearch
