apiVersion: v1
kind: Service
metadata:
  name: kbhbilleder-proxy
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kbhbilleder-proxy
  namespace: production
subsets:
- addresses:
  - ip: 34.117.157.249
  ports:
  - port: 80
    protocol: TCP
