apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo
  namespace: production
  labels:
    component: mongo
spec:
  replicas: 1
  selector:
    component: mongo
  template:
    metadata:
      labels:
        component: mongo
    spec:
      containers:
      - image: mongo:3.6
        name: mongo
        resources:
          limits:
            memory: 200Mi
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - name: mongo-storage
        gcePersistentDisk:
          fsType: ext4
          pdName: mongo-production-disk-new
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: production
  labels:
    component: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    component: mongo
